
services:
  chat_worker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ..:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chat-app  # Pastikan ini sesuai
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db  # Nama service MySQL
      PMA_USER: root
      PMA_PASSWORD: rootpass
  
  # prometheus:
  #   image: prom/prometheus  # Indentasi diperbaiki
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  db_data:
  grafana-storage: